image: node:8.9.0

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

stages:
  - deploy

deployToAWS:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  only:
    - develop
